### ISSUE TITLE
Make updating a MariaDB table from a pandas DataFrame easy

### ISSUE THREAD

**Issue by robertbindar** [MariaDB/mariadb_kernel#11]
Python and pandas are amazingly flexible tools for processing data, it's highly valuable to allow MariaDB kernel users to jump between MariaDB notebooks and Python notebooks whenever they want to use the advantages of either of them.

Currently the kernel allows users to export the content of a query result set into a CSV file (easily importable into a DataFrame) using the `%df` magic command, we should create a similar magic command to permit the reverse too:

`%load new_rows.csv student.grades` for instance could load the content of a CSV file (easily exportable from a DataFrame) into the `student.grades` table.

**Comment by a97410985** [comment]
I want to solve this issue and maybe complete it, can give me some feedback. 😃

**Comment by robertbindar** [comment]
Hey, I saw your Pull Request and I wanted to thank you for your contribution 🎉 . I will submit a review in the next following days for it.
PS: Are these contributions part of GSoC21 application period?

**Comment by a97410985** [comment]
I want to participate in GSoC21, and I found here have some interesting project ideas like 「 Add autocompletion capabilities to the MariaDB Jupyter kernel」 and 「Implement interacting editing of result sets in the MariaDB Jupyter kernel」, so I reading the codebase and well-written document about mariadb_kernel😃 and Jupyter protocol for how kernel communicating with frontend and Widget messaging protocol(for second project idea). I think the best way to get familiar with this project not just by reading, but also write some code and solve some issues, which also can prove my ability😊.
