### ISSUE TITLE
  MariaDB kernel doesn't start in Jupyter-lab

### ISSUE THREAD

**Issue by Agomezroj** [MariaDB/mariadb_kernel#33]
Hello Robert,

I hope you are feeling very well. I wanted to ask you for help if possible with the installation of the Mariadb Kernel in Jupyterlab. I am a statistics student at University National of Colombia and we have tried with several versions of linux and it does not work when executing a code command in jupyterlab.

Could you tell me what operating system you use and installation order or something like that is that it does not work. On the internet there is not even a video of an installation from scratch of the mariadb kernel in jupyterlab.
Especially this one:
[IPKernelApp] ERROR | MariaDB client failed to start
![imagen](https://user-images.githubusercontent.com/92098097/143625586-cdf35b91-5810-43e6-97ab-361be59430bf.png)

**Comment by LinuxJedi** [comment]
Closing this one for now, if you do have any more issues regarding this please feel free to reopen.
