### ISSUE TITLE
It would be nice to support other MySQL compatible servers

### ISSUE THREAD

**Issue by sunxiaoguang** [MariaDB/mariadb_kernel#41]
Looks like we can't connect to other types of MySQL compatible servers at this time. I have created a [PR](https://github.com/MariaDB/mariadb_kernel/pull/40) to let users configure their server name to `MySQL`.

**Comment by grooverdan** [comment]
I think a better strategy is to remove the mariadb client based connector and use a real python connector (like #27).

**Comment by robertbindar** [comment]
New MariaDBClient implementation based on a proper python connector (plus config option) is the ideal solution. Given nobody probably has time to implement that now, @sunxiaoguang fix is just excellent and highly appreciated!

**Comment by LinuxJedi** [comment]
Closing this as #40 is merged. But we should definitely consider #27 too.
